# Custom nav
nav:
  title: "Pluto Nia"

favicon: ""

# Custom background
background:
  color: "#cfd8dc"
  image: ""

# Social media
social:
  Facebook: https://facebook.com/nbl.pro
  Github: https://github.com/nabil48
  Gitlab: https://gitlab.com/nabil48
  Reddit: https://reddit.com/u/nbl_48
  Telegram: https://t.me/nbl_48
  Twitter: https://twitter.com/nbl_48

# Custom footer
# mail: macroid48@gmail.com
copyright: All rights reserved @Clover Tuan & @PlutoNian

# Custom menu. You can specific the path or the card style (only useful for category page).
# Two kinds of card style: 'project-card', 'article-card',
# Never mind the name.
menu:
  # Project:
  #   path: /categories/Projects
  #   card: project-card
  # Stuffs:
  #   path: /tags/Stuffs
  #   card: article-card
  Home: /
  Archive: /archives
  Categories: /categories
  Tags: /tags
  About: /about

# Specific default categories or tags of home page.
# Post which belongs to `category` or `tag` and don't belongs to `except_category` or `except_tag` will be filtered.
home:
  # set card style of home page
  # category: Projects
  # tag: 算法
  # except_category: 树
  # except_tag:
  #   - 总结
  #   - css

card_style:
  home: project-card
  archive: article-card
  tag: article-card
  category: article-card

# category page
category_generator:
  category_per_page: 3
  post_per_category: 5

node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false